name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: beta-0.2.1
  CREATE_VERSION: 0.5.1.b

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-id: dqXDf3W6
          modrinth-featured: false
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Config
          name: "CEI Fabric ${{ env.VERSION }} for Create Fabric ${{ env.MINECRAFT_VERSION }}-${{ env.CREATE_VERSION }}"
          version: ${{ env.VERSION }}
          version-type: beta
          changelog-file: changelog/${{ env.VERSION }}.md
          files: |
            build/libs/*-${{ env.VERSION }}!(-@(dev|sources|slim)).jar

          loaders: |
            fabric
            quilt
          game-versions: |
            ${{ env.MINECRAFT_VERSION }}
          dependencies: |
            create-fabric(required)
          java: |
            ${{ env.JAVA_VERSION }}
          retry-attempts: 2
          retry-delay: 10000
